# Generated by Django 3.2.7 on 2021-09-12 09:56

import Vendeur.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Prénom et nom')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('nci', models.CharField(max_length=200, unique=True, verbose_name="Numéro carte d'identité")),
                ('profile', models.FileField(null=True, upload_to=Vendeur.models.upload_profile)),
            ],
        ),
    ]
